name: CI/CD

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: npm run test
