name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Clean up before building
        run: |
          cd essential-ui
          rm -rf node_modules
          rm -rf dist
      - name: Install dependencies
        run: |
          cd essential-ui
          yarn install
      - name: Lint
        run: |
          cd essential-ui
          yarn lint
      - name: Run Tests
        run: |
          cd essential-ui
          yarn test
      - name: Configure Git
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
      - name: Build
        run: |
          cd essential-ui
          yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}
          BRANCH: gh-pages
          FOLDER: essential-ui/dist
