name: Post-Merge Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: ./templates/common-steps.yml
        with:
          NAME: ${{ github.workflow }}
      - name: Deploy
        run: |
          cd essential-ui
          yarn deploy
