name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: .github/workflows/templates/common-steps.yml
        with:
          NAME: ${{ github.workflow }}
